import { assetUrl } from './config.js';
import { CHAMBRE1_RENDER_STYLES, SEJOUR_RENDER_STYLES } from './renders.js';

const shared = {
  galleryGroups: [
    {
      id: 'sejour', beat: 'sejour',
      photos: [
        { key: 'sejour', source: assetUrl('assets/photos/sejour.jpg'), lead: true },
        { key: 'cuisine', source: assetUrl('assets/photos/cuisine.jpg') },
      ],
      renders: SEJOUR_RENDER_STYLES.map(({ id, source }) => ({ key: `sejour-${id}`, source, style: id })),
    },
    {
      id: 'suite', beat: 'chambre1',
      photos: [
        { key: 'chambre1a', source: assetUrl('assets/photos/chambre-1a.jpg'), lead: true },
        { key: 'chambre1b', source: assetUrl('assets/photos/chambre-1b.jpg') },
        { key: 'salleDeau', source: assetUrl('assets/photos/salle-deau.jpg') },
      ],
      renders: CHAMBRE1_RENDER_STYLES.map(({ id, source }) => ({ key: `chambre1-${id}`, source, style: id })),
    },
    {
      id: 'balcon', beat: 'balcon',
      photos: [{ key: 'balcon', source: assetUrl('assets/photos/balcon.jpg') }],
      renders: [],
    },
    {
      id: 'chambres', beat: 'chambres',
      photos: [
        { key: 'chambre2', source: assetUrl('assets/photos/chambre-2.jpg') },
        { key: 'chambre3', source: assetUrl('assets/renders/chambre3-ia.webp'), type: 'pascalRender' },
      ],
      renders: [],
    },
    {
      id: 'salleDeBains', beat: null,
      photos: [{ key: 'salleDeBains', source: assetUrl('assets/photos/salle-de-bains.jpg') }],
      renders: [],
    },
  ],
  energyChartPaths: [
    ['dpe', assetUrl('assets/diagnostics/dpe.jpeg')],
    ['ges', assetUrl('assets/diagnostics/dpe-ges.jpeg')],
  ],
};

export const COPY = {
  fr: {
    meta: { title: 'Pascal · T4 à Cenon' },
    ui: {
      brand: 'Pascal',
      topline: 'Cenon · T4 · 84,50 m² · 316 500 €',
      walk: 'Visiter librement',
      soon: 'bientôt',
      currentPhoto: 'Photo actuelle',
      photo: 'Photo',
      renderProjection: 'Projection d’aménagement',
      renderStyles: { 'bord-de-mer': 'Bord de mer', boheme: 'Bohème', scandinave: 'Scandinave', japandi: 'Japandi', cosy: 'Cosy' },
      sunTime: 'Heure',
      sunScale: ['7 h', '14 h', '21 h'],
      calibration: 'CALIB', calibrationCopy: 'C copie les valeurs',
      closeWalk: 'Fermer la visite',
      walkHintDesktop: 'Cliquez dans la vue pour regarder · ZQSD / WASD ou flèches pour marcher · Maj pour courir · P libère ou reprend le pointeur · Échap pour revenir',
      walkHintMobile: 'Glissez pour regarder · maintenez le bouton pour avancer · Échap pour revenir',
      walkForward: 'Avancer',
      walkMove: 'marcher',
      walkRun: 'courir',
      walkFreePointer: 'libérer le pointeur',
      walkResumePointer: 'reprendre',
      walkExit: 'quitter',
      walkClick: 'Clic',
      walkLook: 'regarder',
      walkDoorLead: 'ou cliquez pour',
      walkDoorOpen: 'ouvrir',
      walkDoorClose: 'fermer',
      walkDoor: 'la porte',
      planHint: 'Survoler · cliquer pour entrer',
      planOpen: 'Voir le plan',
      planClose: 'Fermer le plan',
      planTapHint: 'Touchez une pièce pour la sélectionner · retouchez pour entrer',
      planEnter: 'Entrer dans',
      planReturn: 'Retour au plan',
      switchLanguage: 'Passer en anglais',
      languageToggle: 'FR / EN',
      download: 'Télécharger le fichier 3D',
      downloadHint: '.glb · 3,7 Mo',
      loading: 'Chargement du modèle…',
      loaded: 'Modèle Pascal chargé',
      fallback: 'La vue 3D est indisponible. Le dossier complet reste accessible ci-dessous.',
      scroll: 'Faire défiler',
      chapters: 'Chapitres',
      goTo: 'Aller à',
      lightboxClose: 'Fermer l’image',
      lightboxPrevious: 'Image précédente',
      lightboxNext: 'Image suivante',
      viewInStory: 'Voir dans la visite →',
    },
    zones: {
      entree: { name: 'Entrée', area: '7,60 m²' },
      sejour: { name: 'Séjour / Cuisine', area: '33,30 m²' },
      chambre1: { name: 'Chambre 1', area: '17,40 m² · avec salle d’eau' },
      salleDeau: { name: 'Salle d’eau', area: 'comprise dans Chambre 1' },
      chambre2: { name: 'Chambre 2', area: '10,50 m²' },
      chambre3: { name: 'Chambre 3', area: '9,40 m²' },
      salleDeBains: { name: 'Salle de bains', area: '4,80 m²' },
      wc: { name: 'WC', area: '1,50 m²' },
      balcon: { name: 'Balcon', area: '8,00 m²' },
    },
    pins: {
      balconyDoor: ['Porte-fenêtre → balcon', ''],
      openKitchen: ['Cuisine ouverte', ''],
      room2: ['Chambre 2', '10,50 m²'],
      room3: ['Chambre 3', '9,40 m²'],
    },
    beats: {
      hero: {
        nav: 'Vue d’ensemble', k: 'À vendre · Cenon — rive droite, Bordeaux',
        h: 'Un 4 pièces lumineux au dernier étage.',
        p: '84,50 m² au 3ᵉ et dernier étage d’une résidence de 2018 — DPE A, à quelques minutes du tram et de la gare. La visite se fait en volume : le modèle 3D que vous parcourez est le relevé de l’appartement.',
        price: '316 500 € · 3 746 € / m²',
        figs: ['84,50 m²', 'T4', '3 chambres', 'Balcon 8 m²', 'Dernier étage', 'Ascenseur', '2018', 'DPE A', 'Place de parking'],
      },
      floor: {
        nav: 'Le niveau', k: 'Un niveau · 84,50 m²',
        h: 'Les pièces de vie d’un côté, les chambres au calme.',
        p: 'L’entrée distribue tout : un séjour-cuisine de 33,30 m² ouvert sur le balcon, trois chambres, deux salles d’eau. Pas un mètre de couloir perdu.',
      },
      sejour: {
        nav: 'Séjour', k: 'Séjour + cuisine · 33,30 m²', h: 'La pièce où tout se passe.',
        p: 'Cuisine ouverte, lumière traversante, et la porte-fenêtre qui file sur le balcon. Ce que vous voyez est le mobilier du modèle — pas un décor.',
      },
      staging: {
        nav: 'Projection', k: 'Projections d’aménagement', h: 'Le séjour, aujourd’hui et demain.',
        p: 'La photo actuelle d’abord, puis trois propositions d’aménagement — rendues depuis le même point de vue, dans le volume réel.',
      },
      balcon: {
        nav: 'Balcon', k: 'Balcon · 8,00 m²', h: 'Le café au soleil du matin.',
        p: 'Huit mètres carrés au-dessus des toits, exposés nord-est. Faites glisser l’heure pour voir la lumière tourner.',
      },
      chambre1: {
        nav: 'Suite', k: 'Suite parentale · 17,40 m²', h: 'Une chambre avec sa salle d’eau à elle.',
        p: 'À l’écart du séjour : la chambre, puis sa salle d’eau privative. La photo est prise du même point de vue que le modèle.',
        photoCaption: 'La chambre aujourd’hui — même point de vue',
      },
      salledeau: {
        nav: 'Salle d’eau', k: 'Salle d’eau · suite parentale', h: 'La salle d’eau attenante.',
        p: 'Douche, vasque et rangements — accessible depuis la chambre par une porte coulissante.',
        photoCaption: 'La salle d’eau aujourd’hui — même point de vue',
      },
      chambres: {
        nav: 'Chambres 2 & 3', k: 'Chambres 2 & 3 · 10,50 et 9,40 m²', h: 'Deux chambres, deux usages.',
        p: 'La chambre 2 donne côté calme. La chambre 3, près du séjour et du balcon, fait une chambre d’enfant ou un bureau idéal.',
      },
      plan: {
        nav: 'Le plan', k: 'Le plan', h: 'Le plan, mais en volume.',
        p: 'Explorez chaque pièce pour l’allumer dans le modèle, puis entrez-y. Le plan est dessiné depuis le modèle Pascal, les surfaces sont celles de la fiche officielle.',
      },
    },
    document: {
      factsK: 'Le bien · en bref', factsH: 'Les chiffres qui comptent.',
      facts: ['316 500 €', '3 746 € / m²', '84,50 m²', 'T4 · 3 chambres', 'Étage 3/3 · ascenseur', 'Balcon · 8 m²', 'Résidence · 2018', 'Place de parking', 'Tram & gare à pied', 'Commerces & écoles'],
      energy: {
        dpe: { label: 'DPE', grade: 'A', value: '48 kWhEP/m²/an', chart: 'DPE — 48 kWhEP/m²/an' },
        ges: { label: 'GES', grade: 'C', value: '11 kgéqCO₂/m²/an', chart: 'GES — 11 kgéqCO₂/m²/an' },
        openChart: 'Voir le graphique officiel',
      },
      surfacesK: 'Surfaces officielles', surfacesH: 'Une mesure, une source.',
      surfacesCaption: 'Surfaces habitables — fiche promoteur.',
      surfaces: [['Entrée', '7,60 m²'], ['Séjour + Cuisine', '33,30 m²'], ['Chambre 1 + salle d’eau', '17,40 m²'], ['Chambre 2', '10,50 m²'], ['Chambre 3', '9,40 m²'], ['Salle de bains', '4,80 m²'], ['WC', '1,50 m²'], ['Total habitable', '84,50 m²'], ['Balcon', '8,00 m²']],
      planAlt: 'Plan promoteur officiel du T4', planCaption: 'Plan officiel — montré comme pièce justificative, non comme illustration principale.',
      galleryK: 'Photos & projections', galleryH: 'L’appartement en images.',
      galleryRows: { photo: 'Photos', projection: 'Projections d’aménagement' },
      galleryTypes: { photo: 'Photo', projection: 'Projection', pascalRender: 'Rendu généré par Pascal' },
      galleryGroups: {
        sejour: { room: 'Séjour & cuisine', area: '33,30 m²' },
        suite: { room: 'Suite parentale', area: '17,40 m²' },
        balcon: { room: 'Balcon', area: '8,00 m²' },
        chambres: { room: 'Chambres 2 & 3', area: '10,50 et 9,40 m²' },
        salleDeBains: { room: 'Salle de bains', area: '4,80 m²' },
      },
      gallery: { sejour: 'Séjour', cuisine: 'Cuisine ouverte', balcon: 'Balcon', chambre1a: 'Chambre 1', chambre1b: 'Chambre 1 · second angle', chambre2: 'Chambre 2', chambre3: 'Chambre 3', salleDeau: 'Salle d’eau', salleDeBains: 'Salle de bains' },
      pascalK: 'Dossier vérifiable', pascalH: 'Un dossier qui se visite.',
      pascalP: 'Cette annonce est construite sur un relevé 3D de l’appartement réalisé avec Pascal : les surfaces, les murs et les menuiseries que vous venez de parcourir sont mesurés. Le fichier 3D est téléchargeable ci-dessous — format .glb, lisible par la plupart des visionneuses 3D.',
    },
    cta: {
      k: 'La suite',
      h: 'Envie de le voir en vrai ?',
      p: 'Contactez l’agence pour organiser une visite — ou pour toute question sur le bien.',
      button: 'Organiser une visite ↗',
      ariaSuffix: 'Ouvre l’annonce de l’agence dans un nouvel onglet',
    },
    footer: { brand: 'Démo Pascal — pascal.app', provenance: 'Données issues d’une annonce publique.' },
  },
  en: {
    meta: { title: 'Pascal · T4 in Cenon' },
    ui: {
      brand: 'Pascal', topline: 'Cenon · 3 bed · 84.50 m² · €316,500', walk: 'Walk through', soon: 'soon', switchLanguage: 'Passer en français', languageToggle: 'EN / FR', download: 'Download the 3D file', downloadHint: '.glb · 3.7 MB', loading: 'Loading the model…', loaded: 'Pascal model loaded', fallback: 'The 3D view is unavailable. The complete file remains accessible below.', scroll: 'Scroll', chapters: 'Chapters', goTo: 'Go to',
      currentPhoto: 'As it is', photo: 'Photo', renderProjection: 'Interior projection',
      renderStyles: { 'bord-de-mer': 'Coastal', boheme: 'Bohemian', scandinave: 'Scandinavian', japandi: 'Japandi', cosy: 'Cosy' },
      sunTime: 'Time', sunScale: ['7:00 AM', '2:00 PM', '9:00 PM'], calibration: 'CALIB', calibrationCopy: 'C copies the values', closeWalk: 'Close walkthrough',
      walkHintDesktop: 'Click the view to look · WASD or arrow keys to walk · Shift to run · P releases or recaptures the pointer · Esc to return',
      walkHintMobile: 'Drag to look · hold the button to move forward · Esc to return',
      walkForward: 'Walk forward', walkMove: 'walk', walkRun: 'run', walkFreePointer: 'free pointer', walkResumePointer: 'resume', walkExit: 'exit', walkClick: 'Click', walkLook: 'look', walkDoorLead: 'or click to', walkDoorOpen: 'open', walkDoorClose: 'close', walkDoor: 'door', planHint: 'Hover · click to enter', planOpen: 'View plan', planClose: 'Close plan', planTapHint: 'Tap a room to select · tap again to enter', planEnter: 'Enter', planReturn: 'Back to plan',
      lightboxClose: 'Close image', lightboxPrevious: 'Previous image', lightboxNext: 'Next image', viewInStory: 'See it in the tour →',
    },
    zones: {
      entree: { name: 'Entrance', area: '7.60 m²' }, sejour: { name: 'Living / Kitchen', area: '33.30 m²' }, chambre1: { name: 'Bedroom 1', area: '17.40 m² · incl. shower room' }, salleDeau: { name: 'Shower room', area: 'included with Bedroom 1' }, chambre2: { name: 'Bedroom 2', area: '10.50 m²' }, chambre3: { name: 'Bedroom 3', area: '9.40 m²' }, salleDeBains: { name: 'Bathroom', area: '4.80 m²' }, wc: { name: 'WC', area: '1.50 m²' }, balcon: { name: 'Balcony', area: '8.00 m²' },
    },
    pins: { balconyDoor: ['Door → balcony', ''], openKitchen: ['Open kitchen', ''], room2: ['Bedroom 2', '10.50 m²'], room3: ['Bedroom 3', '9.40 m²'] },
    beats: {
      hero: { nav: 'Overview', k: 'For sale · Cenon — Bordeaux right bank', h: 'A bright four-room flat on the top floor.', p: '84.50 m² on the third and top floor of a 2018 residence — DPE A, a few minutes from the tram and railway station. The visit unfolds in three dimensions: the 3D model you move through is the measured survey of the flat.', price: '€316,500 · €3,746 / m²', figs: ['84.50 m²', '3 bed', '8 m² balcony', 'Top floor', 'Lift', 'Built 2018', 'DPE A', 'Parking space'] },
      floor: { nav: 'The floor', k: 'One level · 84.50 m²', h: 'Living on one side, bedrooms in the quiet.', p: 'The hall serves everything: a 33.30 m² living-kitchen opening onto the balcony, three bedrooms, two bathrooms. Not a metre of corridor wasted.' },
      sejour: { nav: 'Living', k: 'Living + kitchen · 33.30 m²', h: 'The room where everything happens.', p: 'Open kitchen, light straight through, and the door running out to the balcony. What you see is the model’s own furniture — not set dressing.' },
      staging: { nav: 'Staging', k: 'Interior proposals', h: 'The living room, now and next.', p: 'The current photograph first, followed by three furnishing proposals — rendered from the same viewpoint, within the measured space.' },
      balcon: { nav: 'Balcony', k: 'Balcony · 8.00 m²', h: 'Morning coffee in the sun.', p: 'Eight square metres above the rooftops, facing north-east. Drag the time to watch the light move.' },
      chambre1: { nav: 'Main suite', k: 'Main suite · 17.40 m²', h: 'A bedroom with its own shower room.', p: 'Set apart from the living room: first the bedroom, then its private shower room. The photograph was taken from the same viewpoint as the model.', photoCaption: 'The bedroom today — same viewpoint' },
      salledeau: { nav: 'Shower room', k: 'Shower room · main suite', h: 'The adjoining shower room.', p: 'Shower, vanity and storage — reached from the bedroom through a pocket door.', photoCaption: 'The shower room today — same viewpoint' },
      chambres: { nav: 'Bedrooms 2 & 3', k: 'Bedrooms 2 & 3 · 10.50 and 9.40 m²', h: 'Two bedrooms, two uses.', p: 'Bedroom 2 faces the quiet side. Bedroom 3, close to the living room and balcony, makes an ideal child’s room or home office.' },
      plan: { nav: 'The plan', k: 'The plan', h: 'The plan, but in volume.', p: 'Explore each room to light it up in the model, then enter it. The plan is drawn from the Pascal model; the areas are the official ones.' },
    },
    document: {
      factsK: 'The property · at a glance', factsH: 'The figures that matter.', facts: ['€316,500', '€3,746 / m²', '84.50 m²', '3 bedrooms', 'Floor 3/3 · lift', 'Balcony · 8 m²', 'Built · 2018', 'Parking space', 'Tram & station on foot', 'Shops & schools'],
      energy: {
        dpe: { label: 'DPE', grade: 'A', value: '48 kWhEP/m²/year', chart: 'DPE — 48 kWhEP/m²/year' },
        ges: { label: 'GES', grade: 'C', value: '11 kgCO₂e/m²/year', chart: 'GES — 11 kgCO₂e/m²/year' },
        openChart: 'View official chart',
      },
      surfacesK: 'Official areas', surfacesH: 'One measure, one source.', surfacesCaption: 'Habitable areas — developer’s sheet.', surfaces: [['Entrance', '7.60 m²'], ['Living + Kitchen', '33.30 m²'], ['Bedroom 1 + shower room', '17.40 m²'], ['Bedroom 2', '10.50 m²'], ['Bedroom 3', '9.40 m²'], ['Bathroom', '4.80 m²'], ['WC', '1.50 m²'], ['Total habitable', '84.50 m²'], ['Balcony', '8.00 m²']],
      planAlt: 'Official developer floor plan for the apartment', planCaption: 'Official plan — shown as supporting evidence, not the hero image.',
      galleryK: 'Photos & projections', galleryH: 'The flat in pictures.',
      galleryRows: { photo: 'Photos', projection: 'Staging projections' },
      galleryTypes: { photo: 'Photo', projection: 'Projection', pascalRender: 'Pascal-generated render' },
      galleryGroups: {
        sejour: { room: 'Living room & kitchen', area: '33.30 m²' },
        suite: { room: 'Main suite', area: '17.40 m²' },
        balcon: { room: 'Balcony', area: '8.00 m²' },
        chambres: { room: 'Bedrooms 2 & 3', area: '10.50 and 9.40 m²' },
        salleDeBains: { room: 'Bathroom', area: '4.80 m²' },
      },
      gallery: { sejour: 'Living room', cuisine: 'Open kitchen', balcon: 'Balcony', chambre1a: 'Bedroom 1', chambre1b: 'Bedroom 1 · second angle', chambre2: 'Bedroom 2', chambre3: 'Bedroom 3', salleDeau: 'Shower room', salleDeBains: 'Bathroom' },
      pascalK: 'A verifiable file', pascalH: 'A property file you can walk through.', pascalP: 'This listing is built from a 3D survey of the flat made with Pascal: the areas, walls and joinery you have just explored are measured. The 3D file can be downloaded below in .glb format, readable in most 3D viewers.',
    },
    cta: {
      k: 'Next step',
      h: 'Want to see it for real?',
      p: 'Contact the agency to arrange a visit — or with any question about the property.',
      button: 'Schedule a visit ↗',
      ariaSuffix: 'Opens the agency listing in a new tab',
    },
    footer: { brand: 'Pascal demo — pascal.app', provenance: 'Data from a public listing.' },
  },
};

export { shared as COPY_SHARED };
